### ISSUE TITLE
Village Generation Broken

### ISSUE THREAD

**Issue by WindRider739** [Ivorforce/RecurrentComplex#251]
For some reason, I'm getting a lot of structure issues with villages. Over half of the RC village buildings generate cut in half, or only have a couple of their blocks at all. This seems to be happening in pretty much every biome. 

I'm running a BIOMESOP world, and have the amplitude turned down to 0.250 so the world stays pretty flat. I thought that would help, but apparently I was wrong.

I do not know for sure that RC is causing this, but it seems that only RC buildings are affected. 

Attached is a link to two screenshots. Let me know if I can do anything on my end to get more information.

http://imgur.com/a/lM0HL

**Comment by Ivorforce** [comment]
What version are you running?

**Comment by WindRider739** [comment]
I'm not sure what OTG is. Gonna assume that means no.

RecurrentComplex - 1.4.3.1 - 1.10

**Comment by Ivorforce** [comment]
That's Open Terrain Generator / Biome Bundle.

**Comment by WindRider739** [comment]
No, I am not. Should I be?

**Comment by Ivorforce** [comment]
No, but it's known to have caused issues in the past. I don't know what the current state is there.
Does the issue occur with just ReC installed?

**Comment by WindRider739** [comment]
It does not. But here's the kicker. It doesn't cause issues in single player, but the server I've been building for the last month or so haaaaaaaaaates it.

Is this known to have any issues with sponge?

**Comment by Ivorforce** [comment]
I don't know, but it's worth investigating. Sponge changes up pretty much everything after all.

Try making a new sponge server and seeing if the issue still occurs there. If it does, I'd report it to sponge. If it doesn't, it's probably an update problem with ReC and won't occur in new chunks.

**Comment by WindRider739** [comment]
I'll do that here in a few and report back. It shouldn't be an update error though, simply because these are all new chunks. The server I'm building is an alpha testing ground for a modpack I've been building for quite a while, so it gets wiped pretty much every couple of days.

**Comment by Ivorforce** [comment]
Any update on this?

**Comment by Foxgreat** [comment]
nope, actually with stable sponge 2821 servers, it still bleeding on server-side. 1.12.2 1.4.7

**Comment by Rutes** [comment]
For clarity's sake, might want to mark this as a duplicate with https://github.com/Ivorforce/RecurrentComplex/issues/323
Issue description for 323 is more accurate

**Comment by DanSchlac** [comment]
I was having the same issue for a long time, but I read that spongeforge changes generation and is likely to be the issue. So, even though I had a bunch of mods that required spongeforge I decided to remove spongeforge form my mods folder (both server and client) just to see what happened (I was expecting for it to crash and say that some mods needed spongeforge), but everything loaded and worked correctly with no errors. I made a creative world and flew around to generate some villages in order to see if it worked and I found a bunch of villages all of which generated correctly. So try removing spongeforge from your mods folder and see what happens, that should fix the issue.

**Comment by Yi2nd** [comment]
1

> Any update on this?

Have you checked this? https://github.com/SpongePowered/SpongeForge/issues/1949. There are some replies that might be helpful to solve this issue. By the way, this issue still exists now when using latest version both ReC and spongeforge.

**Comment by M1das2** [comment]
> Any update on this?

Have you checked this? https://github.com/SpongePowered/SpongeForge/issues/1949. There are some replies that might be helpful to solve this issue. By the way, this issue still exists now when using latest version both ReC and spongeforge.

The guy called clienthax has mentioned something that might relates to this issue.
